function B = B_func(in1,in2)
%B_func
%    B = B_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Apr-2026 13:51:47

L = in1(6,:);
f = in1(2,:);
g = in1(3,:);
h = in1(4,:);
k = in1(5,:);
p = in1(1,:);
t2 = cos(L);
t3 = sin(L);
t4 = h.^2;
t5 = k.^2;
t10 = sqrt(p);
t6 = f.*t2;
t7 = k.*t2;
t8 = g.*t3;
t9 = h.*t3;
t12 = t4+t5+1.0;
t11 = -t9;
t13 = t6+t8+1.0;
t14 = t13+1.0;
t15 = t7+t11;
t16 = 1.0./t13;
B = reshape([0.0,t3.*t10,-t2.*t10,0.0,0.0,0.0,t10.^3.*t16.*2.0,t10.*t16.*(f+t2.*t14),t10.*t16.*(g+t3.*t14),0.0,0.0,0.0,0.0,g.*t10.*t15.*t16,-f.*t10.*t15.*t16,(t2.*t10.*t12.*t16)./2.0,(t3.*t10.*t12.*t16)./2.0,-t10.*t15.*t16],[6,3]);
end
